#
# Build HTML documentation and upload it to GitHub Pages
#

name: Build and deploy documentation

on:
  push:
    paths:
      - 'documentation/**/*.rst'
      - 'documentation/**/conf.py'

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add sphinx dependencies
        run: |
          echo furo >> documentation/requirements.txt
          echo sphinx-copybutton >> documentation/requirements.txt

      - name: Build documentation
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation"

      - name: Bypassing Jekyll on GH pages
        run: |
          sudo touch documentation/_build/html/.nojekyll

      - name: Deploy documents to GH pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/_build/html
