name: libraries-test-suite

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  libraries-test-suite:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          path: od
          submodules: recursive

      - uses: dylan-lang/install-opendylan@v2
        with:
          version: 2022.1
          tag: v2022.1.0

      - name: Build libraries-test-suite-app
        run: |
          # We want to use the registry in the sources directory...
          cd od/sources
          ../../dylan-compiler -build -jobs 3 libraries-test-suite-app

      - name: Run libraries-test-suite-app
        run: |
          od/sources/_build/bin/libraries-test-suite-app --tag=-benchmark
